In [7]:
import pandas as pd

In [8]:
general_df = pd.read_csv('./generalizability/ldaMataveMetrics.csv')

In [9]:
calibrated_dfs = []
for dataset in general_df['dataset'].value_counts().keys().tolist():
    temp_df = general_df[general_df['dataset'] == dataset]
    temp_df = temp_df.drop(columns='dataset')

    # Get metric columns. 
    metric_cols = [c for c in temp_df.columns if 'model' not in c]
    # Extract real rows.
    real_mask = temp_df['model'].str.startswith('real')
    real_df = temp_df.loc[real_mask, metric_cols]

    # Get mean and standard deviation. 
    mean = real_df.mean()
    std_dev = real_df.std(ddof=1)
    # Avoid divide by zero.
    std_dev = std_dev.replace(0, 1e-8)



    # Reliability is inverse variance. 
    reliability = 1 / std_dev**2

    weights = reliability / reliability.sum()
    weight_rank = weights.rank(ascending=False, method="dense").astype(int)
    # Calibrate scores. 
    calibrated = temp_df.copy()
    for m in metric_cols:
        calibrated[m] = ((temp_df[m] - mean[m]) / std_dev[m])
        calibrated[f"rank_{m}"] = weight_rank[m]

    calibrated["final_score"] = (
        calibrated[metric_cols] * weights
    ).sum(axis=1)

    calibrated['dataset'] = dataset

    calibrated_dfs.append(calibrated)

In [10]:
calibrated_results = pd.concat(calibrated_dfs)
calibrated_results

,model,CHI,ZIPF,CLASSIFIER,IRPR,FID,PR,DC,MAUVE,TRADITIONAL,...,rank_CLASSIFIER,rank_IRPR,rank_FID,rank_PR,rank_DC,rank_MAUVE,rank_TRADITIONAL,rank_ZERO,final_score,dataset
0,LDA,-5.636972e+06,45.287521,3.671598,11.564781,18.570181,204.958881,9.079844,117.144949,14.180594,...,10,3,7,4,8,6,9,2,-5.636972e+06,yahoo
1,MATAVE,-8.340858e+05,84.609292,4.307750,15.002829,20.686738,220.714097,8.272847,127.382847,26.562514,...,10,3,7,4,8,6,9,2,-8.340858e+05,yahoo
2,combinedTopicModel,-4.628214e+04,59.422155,3.548525,13.679438,15.818661,123.243023,9.194088,118.322146,16.165381,...,10,3,7,4,8,6,9,2,-4.628214e+04,yahoo
3,realToReal,0.000000e+00,-1.052020,-0.382261,1.132477,1.141413,-0.006836,1.151035,-0.622905,-0.786369,...,10,3,7,4,8,6,9,2,-3.438382e-11,yahoo
4,realToReal2,0.000000e+00,0.113771,1.134744,-0.370991,-0.721977,-0.996565,-0.655138,1.153469,-0.339085,...,10,3,7,4,8,6,9,2,-3.584212e-11,yahoo
5,realToReal3,0.000000e+00,0.938249,-0.752484,-0.761486,-0.419436,1.003400,-0.495896,-0.530564,1.125454,...,10,3,7,4,8,6,9,2,7.022594e-11,yahoo
6,LDA,-3.880162e+03,43.444244,3.207581,15.487224,56.088133,31.321924,88.215020,128.074400,32.591137,...,10,4,6,9,5,7,8,2,-3.731196e+03,banking77
7,MATAVE,-3.856662e+03,60.190278,3.876452,23.293524,78.692933,39.131934,185.066338,162.015016,45.129464,...,10,4,6,9,5,7,8,2,-3.707385e+03,banking77
8,combinedTopicModel,-1.953765e+02,56.346192,3.440207,18.923769,57.913300,27.536213,127.498001,119.862121,37.442921,...,10,4,6,9,5,7,8,2,-1.856855e+02,banking77
9,realToReal,5.773503e-01,1.093215,0.968353,-0.076028,0.231627,0.145823,-0.417914,-0.556193,-0.404111,...,10,4,6,9,5,7,8,2,5.724558e-01,banking77
10,realToReal2,5.773503e-01,-0.224644,-1.028896,-0.959816,-1.095488,-1.064905,1.141165,-0.598253,1.138816,...,10,4,6,9,5,7,8,2,5.416611e-01,banking77
11,realToReal3,-1.154701e+00,-0.868571,0.060543,1.035844,0.863861,0.919082,-0.723251,1.154445,-0.734706,...,10,4,6,9,5,7,8,2,-1.114117e+00,banking77
12,LDA,-1.000000e+08,2.158958,116.560738,0.414546,9.330945,14.360784,0.918283,48.244084,13.649577,...,3,2,9,8,7,6,10,5,-1.000000e+08,medicalAbstracts
13,MATAVE,-1.000000e+08,-0.879653,143.082519,2.623999,37.130355,51.856648,26.946640,167.610547,15.026525,...,3,2,9,8,7,6,10,5,-1.000000e+08,medicalAbstracts
14,combinedTopicModel,-1.000000e+08,-0.811009,121.563566,0.258148,8.146523,14.728011,0.634549,31.089057,15.870916,...,3,2,9,8,7,6,10,5,-1.000000e+08,medicalAbstracts
15,realToReal,0.000000e+00,-0.187820,0.144517,-0.748509,-0.293162,1.025106,-0.948589,-0.200145,-1.056397,...,3,2,9,8,7,6,10,5,-1.872660e-11,medicalAbstracts
16,realToReal2,0.000000e+00,-0.892772,0.919879,-0.387192,-0.820653,-0.972844,-0.095911,-0.884791,0.931954,...,3,2,9,8,7,6,10,5,-6.928786e-12,medicalAbstracts
17,realToReal3,0.000000e+00,1.080593,-1.064396,1.135701,1.113815,-0.052262,1.044500,1.084936,0.124444,...,3,2,9,8,7,6,10,5,2.565538e-11,medicalAbstracts
18,LDA,-1.000000e+08,124.040024,17.107979,45.640994,177.492603,88.878935,26.111061,127.067941,33.839071,...,9,2,3,6,10,5,8,7,-1.000000e+08,dementiaAudio
19,MATAVE,-1.000000e+08,186.727496,17.107979,76.390594,271.196268,82.680667,27.264134,126.686627,29.224402,...,9,2,3,6,10,5,8,7,-1.000000e+08,dementiaAudio
20,combinedTopicModel,-1.000000e+08,150.387361,17.107979,56.962454,193.688368,75.373502,26.344368,126.426236,30.128192,...,9,2,3,6,10,5,8,7,-1.000000e+08,dementiaAudio
21,realToReal,0.000000e+00,0.585474,-0.820501,0.888767,1.146774,0.188778,0.675187,-0.229121,0.368493,...,9,2,3,6,10,5,8,7,1.515772e-10,dementiaAudio
22,realToReal2,0.000000e+00,0.569188,-0.293371,0.194029,-0.690358,0.892157,0.473635,1.094677,-1.131959,...,9,2,3,6,10,5,8,7,8.142213e-12,dementiaAudio
23,realToReal3,0.000000e+00,-1.154662,1.113872,-1.082796,-0.456416,-1.080934,-1.148822,-0.865556,0.763466,...,9,2,3,6,10,5,8,7,-1.597195e-10,dementiaAudio
24,LDA,-4.158073e-01,18.790002,9.838899,-0.022159,26.167081,21.856224,6.567964,40.310115,15.352127,...,10,2,3,7,6,8,9,5,-4.158073e-01,huffPostNews
25,MATAVE,-5.869329e+03,13.724703,10.512605,-7.276941,22.017423,65.665039,1.812015,43.281709,27.192298,...,10,2,3,7,6,8,9,5,-5.869329e+03,huffPostNews
26,combinedTopicModel,0.000000e+00,14.121439,9.515040,1.350439,22.552301,31.452254,4.470340,42.882653,18.142052,...,10,2,3,7,6,8,9,5,4.780399e-10,huffPostNews
27,realToReal,0.000000e+00,-0.040497,0.214401,-0.340353,0.883247,0.562122,0.410265,0.181239,-0.409419,...,10,2,3,7,6,8,9,5,-3.930837e-11,huffPostNews
28,realToReal2,0.000000e+00,-0.979136,0.875411,-0.785396,-1.085755,-1.154568,-1.139885,0.896986,1.139740,...,10,2,3,7,6,8,9,5,-1.216336e-10,huffPostNews
29,realToReal3,0.000000e+00,1.019633,-1.089811,1.125750,0.202508,0.592446,0.729620,-1.078225,-0.730321,...,10,2,3,7,6,8,9,5,1.609420e-10,huffPostNews
30,LDA,-6.666580e+07,11.356319,8.193591,6.392001,35.460604,23.790623,28.213822,238.624108,15.396764,...,10,4,5,8,6,3,7,9,-6.666580e+07,clinc150
31,MATAVE,-9.218171e+07,32.699620,8.245935,5.229036,38.236670,32.302909,19.076670,247.211348,14.305357,...,10,4,5,8,6,3,7,9,-9.218171e+07,clinc150
32,combinedTopicModel,-7.848254e+07,5.538247,7.078538,6.188752,34.978132,25.543651,21.289680,236.931977,15.853992,...,10,4,5,8,6,3,7,9,-7.848254e+07,clinc150
33,realToReal,0.000000e+00,-0.171228,-1.097121,0.386692,-0.306177,0.160591,-0.140344,0.078589,-0.672586,...,10,4,5,8,6,3,7,9,-1.703581e-12,clinc150
34,realToReal2,0.000000e+00,1.074558,0.236720,-1.135605,-0.811117,-1.070577,-0.922414,-1.036976,-0.476555,...,10,4,5,8,6,3,7,9,-1.632942e-12,clinc150
35,realToReal3,0.000000e+00,-0.903330,0.860401,0.748913,1.117294,0.909986,1.062758,0.958387,1.149141,...,10,4,5,8,6,3,7,9,3.336523e-12,clinc150
36,LDA,-3.853314e+00,-0.048692,10.144305,14.936800,85.557287,89.968536,12.540592,177.245085,32.301404,...,9,1,2,4,7,3,8,5,4.131570e+01,syntheticCareHomeNurseNotes
37,MATAVE,-9.359219e-01,9.367771,7.605827,11.302070,41.698043,22.089216,12.655896,66.333074,19.466905,...,9,1,2,4,7,3,8,5,2.064469e+01,syntheticCareHomeNurseNotes
38,combinedTopicModel,-2.234724e-01,7.529285,8.835822,11.138295,39.237470,22.085624,6.421903,25.632428,21.795025,...,9,1,2,4,7,3,8,5,1.698384e+01,syntheticCareHomeNurseNotes
39,realToReal,-6.366901e-01,0.769189,1.141456,-0.535342,-0.237352,1.147381,0.850505,-0.347273,-0.380713,...,9,1,2,4,7,3,8,5,-4.019681e-01,syntheticCareHomeNurseNotes
40,realToReal2,-5.159026e-01,0.361235,-0.721752,-0.618363,-0.859970,-0.686107,-1.101626,1.127340,1.134440,...,9,1,2,4,7,3,8,5,-4.999847e-01,syntheticCareHomeNurseNotes
41,realToReal3,1.152593e+00,-1.130424,-0.419704,1.153705,1.097322,-0.461274,0.251121,-0.780067,-0.753726,...,9,1,2,4,7,3,8,5,9.019528e-01,syntheticCareHomeNurseNotes
42,LDA,-9.819593e+07,49.196731,7.395803,21.219789,54.131692,36.583463,3.607141,26.123077,8.550559,...,10,3,4,6,8,9,7,5,-9.819593e+07,clinicalDialogueSummarizations
43,MATAVE,-9.123134e+07,137.588386,7.446802,28.270390,67.352963,33.391100,18.405639,25.703612,11.713556,...,10,3,4,6,8,9,7,5,-9.123134e+07,clinicalDialogueSummarizations
44,combinedTopicModel,-1.805620e+07,84.018708,6.672280,23.112911,52.352832,26.980767,6.777859,16.801070,9.284126,...,10,3,4,6,8,9,7,5,-1.805620e+07,clinicalDialogueSummarizations
45,realToReal,0.000000e+00,0.098621,-1.154615,0.619368,-1.131639,0.080664,-1.141602,-0.335904,0.681376,...,10,3,4,6,8,9,7,5,9.950820e-12,clinicalDialogueSummarizations
46,realToReal2,0.000000e+00,-1.045657,0.589470,-1.153655,0.764679,0.957225,0.420605,1.124705,-1.148026,...,10,3,4,6,8,9,7,5,-8.059974e-11,clinicalDialogueSummarizations
47,realToReal3,0.000000e+00,0.947035,0.565145,0.534287,0.366960,-1.037889,0.720997,-0.788801,0.466650,...,10,3,4,6,8,9,7,5,7.064892e-11,clinicalDialogueSummarizations
48,LDA,-1.000000e+08,49.720125,12.629676,33.796271,52.823981,76.812668,144.412638,21.725222,32.248963,...,9,3,4,6,5,10,7,8,-1.000000e+08,simSUM
49,MATAVE,-1.000000e+08,124.779795,13.453145,35.519526,63.946587,77.378698,141.974299,22.495811,34.063413,...,9,3,4,6,5,10,7,8,-1.000000e+08,simSUM
50,combinedTopicModel,-1.000000e+08,101.752045,12.951049,33.225724,48.712896,74.418150,141.213319,15.176864,36.958170,...,9,3,4,6,5,10,7,8,-1.000000e+08,simSUM
51,realToReal,0.000000e+00,-1.154644,0.431741,-0.448833,-0.705391,0.214008,-0.097132,-0.407579,0.849429,...,9,3,4,6,5,10,7,8,-9.710873e-11,simSUM
52,realToReal2,0.000000e+00,0.587179,0.711599,-0.696947,-0.439023,-1.089679,1.045022,-0.731844,-1.102101,...,9,3,4,6,5,10,7,8,2.314100e-11,simSUM
53,realToReal3,0.000000e+00,0.567465,-1.143340,1.145781,1.144414,0.875671,-0.947890,1.139423,0.252672,...,9,3,4,6,5,10,7,8,7.396773e-11,simSUM
54,LDA,-4.550553e+00,12.078337,8.287009,72.034153,36.329755,36.917473,11.190359,31.497704,88.006386,...,8,1,4,5,9,7,3,2,7.391821e+01,atis
55,MATAVE,-4.550553e+00,16.903704,9.119978,97.313948,44.432442,37.439491,14.212583,27.611711,78.983950,...,8,1,4,5,9,7,3,2,9.225358e+01,atis
56,combinedTopicModel,-4.550553e+00,15.134715,8.308573,79.198815,36.494658,30.397069,12.436239,29.708607,76.841002,...,8,1,4,5,9,7,3,2,7.760996e+01,atis
57,realToReal,1.132372e+00,0.889455,-0.429073,-1.118226,0.329598,-0.213703,1.154687,1.137425,-1.039391,...,8,1,4,5,9,7,3,2,-1.086869e+00,atis
58,realToReal2,-7.618904e-01,0.192965,1.142934,0.309757,0.793598,1.089576,-0.582273,-0.396380,0.955298,...,8,1,4,5,9,7,3,2,3.471698e-01,atis
59,realToReal3,-3.704817e-01,-1.082420,-0.713861,0.808469,-1.123195,-0.875874,-0.572414,-0.741045,0.084093,...,8,1,4,5,9,7,3,2,7.396989e-01,atis

In [11]:
calibrated_results.to_csv('./generalizability.csv')

In [14]:
ranked_dict_results = []
for dataset in calibrated_results['dataset'].unique():
    subset = calibrated_results[calibrated_results['dataset'] == dataset]
    # Extract not real rows.
    real_mask = subset['model'].str.startswith('real')
    subset = subset.loc[~real_mask]
    ranks = subset['final_score'].rank(
        ascending=False,
        method='dense'
    ).astype(int)
    ranked_dict_results.append(pd.DataFrame({
        'model': subset['model'].values,
        'dataset': dataset,
        'final_score': subset['final_score'].values,
        'rank': ranks.values
    }))

In [15]:
pd.concat(ranked_dict_results)

                model                         dataset   final_score  rank
0                 LDA                           yahoo -5.636972e+06     3
1              MATAVE                           yahoo -8.340858e+05     2
2  combinedTopicModel                           yahoo -4.628214e+04     1
0                 LDA                       banking77 -3.731196e+03     3
1              MATAVE                       banking77 -3.707385e+03     2
2  combinedTopicModel                       banking77 -1.856855e+02     1
0                 LDA                medicalAbstracts -1.000000e+08     1
1              MATAVE                medicalAbstracts -1.000000e+08     1
2  combinedTopicModel                medicalAbstracts -1.000000e+08     1
0                 LDA                   dementiaAudio -1.000000e+08     3
1              MATAVE                   dementiaAudio -1.000000e+08     1
2  combinedTopicModel                   dementiaAudio -1.000000e+08     2
0                 LDA                    huffPostNews -4.158073e-01     2
1              MATAVE                    huffPostNews -5.869329e+03     3
2  combinedTopicModel                    huffPostNews  4.780399e-10     1
0                 LDA                        clinc150 -6.666580e+07     1
1              MATAVE                        clinc150 -9.218171e+07     3
2  combinedTopicModel                        clinc150 -7.848254e+07     2
0                 LDA     syntheticCareHomeNurseNotes  4.131570e+01     1
1              MATAVE     syntheticCareHomeNurseNotes  2.064469e+01     2
2  combinedTopicModel     syntheticCareHomeNurseNotes  1.698384e+01     3
0                 LDA  clinicalDialogueSummarizations -9.819593e+07     3
1              MATAVE  clinicalDialogueSummarizations -9.123134e+07     2
2  combinedTopicModel  clinicalDialogueSummarizations -1.805620e+07     1
0                 LDA                          simSUM -1.000000e+08     2
1              MATAVE                          simSUM -1.000000e+08     1
2  combinedTopicModel                          simSUM -1.000000e+08     1
0                 LDA                            atis  7.391821e+01     3
1              MATAVE                            atis  9.225358e+01     1
2  combinedTopicModel                            atis  7.760996e+01     2