In [1]:
import pandas as pd
import numpy as np

In [2]:
general_df = pd.read_csv('./generalizability/ldaMataveMetrics.csv')

In [3]:
general_df

,dataset,model,CHI,ZIPF,CLASSIFIER,IRPR,FID,PR,DC,MAUVE,TRADITIONAL,ZERO
0,yahoo,LDA,9.436303e-01,0.122554,0.888889,0.412986,1.012399,0.349915,0.103568,0.713425,0.374836,0.270910
1,yahoo,MATAVE,9.916591e-01,0.222275,0.962963,0.416155,1.028472,0.376042,0.096035,0.772034,0.562229,0.295235
2,yahoo,combinedTopicModel,9.995372e-01,0.158400,0.874558,0.414935,0.991504,0.214404,0.104635,0.720164,0.404874,0.252905
3,yahoo,realToReal,1.000000e+00,0.005036,0.416854,0.403372,0.880048,0.010016,0.029556,0.039246,0.148319,0.100081
4,yahoo,realToReal2,1.000000e+00,0.007992,0.593496,0.401987,0.865898,0.008375,0.012696,0.049415,0.155089,0.101293
5,yahoo,realToReal3,1.000000e+00,0.010083,0.373745,0.401627,0.868195,0.011692,0.014183,0.039774,0.177254,0.101734
6,banking77,LDA,2.776298e-13,0.131400,0.903989,0.310814,0.615170,0.382805,0.308852,0.703925,0.365555,0.147635
7,banking77,MATAVE,6.055634e-03,0.176033,0.991870,0.337082,0.716313,0.469054,0.637870,0.882104,0.445697,0.220855
8,banking77,combinedTopicModel,9.495060e-01,0.165787,0.934553,0.322378,0.623337,0.340998,0.442302,0.660813,0.396567,0.186324
9,banking77,realToReal,1.000000e+00,0.018521,0.609782,0.258443,0.365246,0.038515,0.007754,0.028652,0.154659,0.084253
10,banking77,realToReal2,1.000000e+00,0.015009,0.347368,0.255469,0.359308,0.025145,0.013050,0.028431,0.164521,0.079313
11,banking77,realToReal3,9.995537e-01,0.013292,0.490507,0.262185,0.368075,0.047055,0.006717,0.037632,0.152546,0.081038
12,medicalAbstracts,LDA,0.000000e+00,0.014930,0.821622,0.354773,0.708207,0.159788,0.034525,0.285763,0.501198,0.532371
13,medicalAbstracts,MATAVE,0.000000e+00,0.004101,0.905602,0.360913,0.972905,0.501161,0.197862,0.955450,0.533052,0.494359
14,medicalAbstracts,combinedTopicModel,0.000000e+00,0.004346,0.837463,0.354339,0.696929,0.163132,0.032745,0.189518,0.552586,0.519747
15,medicalAbstracts,realToReal,1.000000e+00,0.006567,0.452991,0.351541,0.616568,0.038377,0.022810,0.013975,0.160999,0.105775
16,medicalAbstracts,realToReal2,1.000000e+00,0.004054,0.455447,0.352545,0.611546,0.020187,0.028161,0.010134,0.206996,0.110598
17,medicalAbstracts,realToReal3,1.000000e+00,0.011087,0.449163,0.356777,0.629965,0.028568,0.035317,0.021185,0.188316,0.113702
18,dementiaAudio,LDA,0.000000e+00,0.275123,1.000000,0.268766,0.528872,0.971628,0.945400,0.994716,0.831707,0.291172
19,dementiaAudio,MATAVE,0.000000e+00,0.408289,1.000000,0.298694,0.678668,0.918791,0.985177,0.991864,0.742608,0.248349
20,dementiaAudio,combinedTopicModel,0.000000e+00,0.331092,1.000000,0.279785,0.554763,0.856502,0.953449,0.989917,0.760059,0.260540
21,dementiaAudio,realToReal,1.000000e+00,0.012869,0.502874,0.225210,0.246963,0.215590,0.067963,0.042560,0.185468,0.092006
22,dementiaAudio,realToReal2,1.000000e+00,0.012835,0.517491,0.224534,0.244026,0.221586,0.061010,0.052462,0.156498,0.080851
23,dementiaAudio,realToReal3,1.000000e+00,0.009173,0.556511,0.223291,0.244400,0.204767,0.005042,0.037800,0.193094,0.102939
24,huffPostNews,LDA,1.000000e+00,0.094843,0.903994,0.398165,0.932179,0.256034,0.113738,0.668309,0.408341,0.261322
25,huffPostNews,MATAVE,9.999413e-01,0.072751,0.933262,0.391973,0.914629,0.685871,0.069518,0.715154,0.596367,0.333143
26,huffPostNews,combinedTopicModel,1.000000e+00,0.074481,0.889925,0.399336,0.916891,0.350187,0.094235,0.708863,0.452646,0.263551
27,huffPostNews,realToReal,1.000000e+00,0.012715,0.485879,0.397893,0.825248,0.047104,0.056485,0.035705,0.158042,0.108758
28,huffPostNews,realToReal2,1.000000e+00,0.008621,0.514595,0.397513,0.816921,0.030260,0.042072,0.046989,0.182643,0.094002
29,huffPostNews,realToReal3,1.000000e+00,0.017338,0.429221,0.399145,0.822369,0.047402,0.059454,0.015851,0.152946,0.095095
30,clinc150,LDA,3.333420e-01,0.040010,0.905848,0.370837,0.903597,0.370109,0.267718,0.856025,0.297910,0.230938
31,clinc150,MATAVE,7.818290e-02,0.092056,0.908059,0.365799,0.918988,0.485963,0.192195,0.885654,0.287830,0.200108
32,clinc150,combinedTopicModel,2.151746e-01,0.025822,0.858749,0.369956,0.900922,0.393968,0.210487,0.850187,0.302133,0.212636
33,clinc150,realToReal,1.000000e+00,0.011899,0.513418,0.344821,0.705288,0.048500,0.033357,0.032981,0.149495,0.096747
34,clinc150,realToReal2,1.000000e+00,0.014937,0.569758,0.338226,0.702489,0.031744,0.026893,0.029132,0.151305,0.090212
35,clinc150,realToReal3,1.000000e+00,0.010114,0.596101,0.346390,0.713181,0.058700,0.043301,0.036017,0.166320,0.070286
36,syntheticCareHomeNurseNotes,LDA,1.776357e-15,0.014840,0.950396,0.313259,0.675701,0.687813,0.222372,0.774940,0.681963,0.241079
37,syntheticCareHomeNurseNotes,MATAVE,5.827899e-01,0.120457,0.832427,0.308065,0.544897,0.197927,0.224177,0.314331,0.475706,0.100687
38,syntheticCareHomeNurseNotes,combinedTopicModel,7.251117e-01,0.099836,0.889588,0.307831,0.537559,0.197901,0.126569,0.145305,0.513120,0.161325
39,syntheticCareHomeNurseNotes,realToReal,6.425657e-01,0.024013,0.532011,0.291150,0.419830,0.046790,0.039335,0.037413,0.156743,0.087810
40,syntheticCareHomeNurseNotes,realToReal2,6.666947e-01,0.019438,0.445422,0.291032,0.417973,0.033557,0.008770,0.043537,0.181092,0.086340
41,syntheticCareHomeNurseNotes,realToReal3,1.000000e+00,0.002707,0.459459,0.293564,0.423811,0.035180,0.029950,0.035616,0.150748,0.100210
42,clinicalDialogueSummarizations,LDA,1.804066e-02,0.067664,0.882244,0.324126,0.700172,0.346687,0.152044,0.670578,0.317777,0.289476
43,clinicalDialogueSummarizations,MATAVE,8.768662e-02,0.174165,0.884921,0.343103,0.754790,0.322953,0.491114,0.660508,0.373124,0.379120
44,clinicalDialogueSummarizations,combinedTopicModel,8.194380e-01,0.109620,0.844266,0.329221,0.692824,0.275295,0.224693,0.446787,0.330613,0.307443
45,clinicalDialogueSummarizations,realToReal,1.000000e+00,0.008507,0.433427,0.268679,0.471876,0.075303,0.043239,0.035384,0.180081,0.107883
46,clinicalDialogueSummarizations,realToReal2,1.000000e+00,0.007129,0.524975,0.263907,0.479710,0.081820,0.079033,0.070449,0.148069,0.107989
47,clinicalDialogueSummarizations,realToReal3,1.000000e+00,0.009529,0.523699,0.268450,0.478067,0.066987,0.085916,0.024512,0.176323,0.095942
48,simSUM,LDA,0.000000e+00,0.065586,0.948246,0.238410,0.453070,0.703834,0.914490,0.850609,0.487842,0.365717
49,simSUM,MATAVE,0.000000e+00,0.153250,0.975580,0.241777,0.516674,0.708391,0.899407,0.879122,0.506891,0.355691
50,simSUM,combinedTopicModel,0.000000e+00,0.126356,0.958913,0.237296,0.429561,0.684556,0.894699,0.608304,0.537282,0.344105
51,simSUM,realToReal,1.000000e+00,0.006168,0.543346,0.171518,0.146968,0.087157,0.020543,0.031643,0.158191,0.107454
52,simSUM,realToReal2,1.000000e+00,0.008202,0.552635,0.171034,0.148491,0.076661,0.027608,0.019644,0.137703,0.082215
53,simSUM,realToReal3,1.000000e+00,0.008179,0.491062,0.174633,0.157546,0.092484,0.015280,0.088886,0.151926,0.085165
54,atis,LDA,0.000000e+00,0.160100,0.924510,0.273549,0.499266,0.445983,0.649656,0.930024,0.391046,0.281507
55,atis,MATAVE,0.000000e+00,0.214378,0.965789,0.291243,0.556121,0.451170,0.812388,0.820226,0.367406,0.206154
56,atis,combinedTopicModel,0.000000e+00,0.194480,0.925578,0.278564,0.500423,0.381192,0.716741,0.879474,0.361791,0.232350
57,atis,realToReal,1.000000e+00,0.034241,0.492565,0.222348,0.246657,0.077028,0.109284,0.072197,0.157731,0.066055
58,atis,realToReal2,6.666748e-01,0.026406,0.570469,0.223348,0.249913,0.089978,0.015758,0.028859,0.162957,0.069030
59,atis,realToReal3,7.355493e-01,0.012060,0.478451,0.223697,0.236463,0.070448,0.016289,0.019121,0.160675,0.070581

In [4]:
calibrated_dfs = []
for dataset in general_df['dataset'].value_counts().keys().tolist():
    temp_df = general_df[general_df['dataset'] == dataset]
    temp_df = temp_df.drop(columns='dataset')

    # Get metric columns. 
    metric_cols = [c for c in temp_df.columns if 'model' not in c]
    # Extract real rows.
    real_mask = temp_df['model'].str.startswith('real')
    real_df = temp_df.loc[real_mask, metric_cols]

    # There should be a minimum standard deviation, otherwise the metric is returning all 0s or exhibits no variation (which we assume is not indicative of a perfect metric, but a failing one).
    min_std = 1e-6
    # Get standard deviation. 
    std_dev = real_df.std(ddof=1)
    # Get mean. 
    mean = real_df.mean()

    # Remove saturated metrics
    valid_metrics = pd.Series(True, index=metric_cols)
    for m in metric_cols:
        # Real-vs-real values for this metric
        real_values = real_df[m]
        # Detect saturation at minimum or maximum or standard deviation is less than min_std
        if (np.allclose(real_values, 1, atol=min_std)
            or np.allclose(real_values, 0, atol=min_std)
            or std_dev[m] < min_std
        ):
            valid_metrics[m] = False

    # Get validity weights (as inverse score such that lower scores get higher weight) and remove saturated metrics. 
    validity_weights  = (1 - mean).where(valid_metrics, 0)
    # Normalize (relative importance, not arbitrary magnitude). 
    validity_weights = validity_weights / validity_weights.sum()

    # Get reliability weights (coefficient of variation, which is dimensionless and scale invariant).
    safe_std = std_dev.clip(lower=min_std)
    reliability_weights = 1 / (1 + (safe_std / mean))
    # Remove saturated metrics. 
    reliability_weights = reliability_weights.where(valid_metrics, 0)
    # Normalize (relative importance, not arbitrary magnitude). 
    reliability_weights = reliability_weights / reliability_weights.sum()

    # Combine weights. 
    weights = (validity_weights + reliability_weights) / 2
    # Normalize (relative importance, not arbitrary magnitude). 
    weights = weights / weights.sum()

    weight_rank = weights.rank(ascending=False, method="dense").astype(int)
    
    # Calibrate scores.
    calibrated = temp_df.copy()

    for m in metric_cols:
        calibrated[f'weighted_{m}'] = (
            calibrated[m] * weights[m]
        )
        calibrated[f"rank_{m}"] = weight_rank[m]
        calibrated[f"weight_{m}"] = weights[m]

    calibrated["final_score"] = (
        calibrated[metric_cols] * weights
    ).sum(axis=1)

    calibrated['dataset'] = dataset

    calibrated_dfs.append(calibrated)

In [5]:
weights

CHI            0.062302
ZIPF           0.103822
CLASSIFIER     0.086267
IRPR           0.110030
FID            0.107173
PR             0.112713
DC             0.089285
MAUVE          0.096971
TRADITIONAL    0.113267
ZERO           0.118169
dtype: float64

In [6]:
calibrated_results = pd.concat(calibrated_dfs)
calibrated_results

,model,CHI,ZIPF,CLASSIFIER,IRPR,FID,PR,DC,MAUVE,TRADITIONAL,...,rank_MAUVE,weight_MAUVE,weighted_TRADITIONAL,rank_TRADITIONAL,weight_TRADITIONAL,weighted_ZERO,rank_ZERO,weight_ZERO,final_score,dataset
0,LDA,9.436303e-01,0.122554,0.888889,0.412986,1.012399,0.349915,0.103568,0.713425,0.374836,...,3,0.125273,0.044534,5,0.118810,0.034688,1,0.128043,0.436236,yahoo
1,MATAVE,9.916591e-01,0.222275,0.962963,0.416155,1.028472,0.376042,0.096035,0.772034,0.562229,...,3,0.125273,0.066798,5,0.118810,0.037803,1,0.128043,0.491467,yahoo
2,combinedTopicModel,9.995372e-01,0.158400,0.874558,0.414935,0.991504,0.214404,0.104635,0.720164,0.404874,...,3,0.125273,0.048103,5,0.118810,0.032383,1,0.128043,0.423069,yahoo
3,realToReal,1.000000e+00,0.005036,0.416854,0.403372,0.880048,0.010016,0.029556,0.039246,0.148319,...,3,0.125273,0.017622,5,0.118810,0.012815,1,0.128043,0.184721,yahoo
4,realToReal2,1.000000e+00,0.007992,0.593496,0.401987,0.865898,0.008375,0.012696,0.049415,0.155089,...,3,0.125273,0.018426,5,0.118810,0.012970,1,0.128043,0.199867,yahoo
5,realToReal3,1.000000e+00,0.010083,0.373745,0.401627,0.868195,0.011692,0.014183,0.039774,0.177254,...,3,0.125273,0.021059,5,0.118810,0.013026,1,0.128043,0.182596,yahoo
6,LDA,2.776298e-13,0.131400,0.903989,0.310814,0.615170,0.382805,0.308852,0.703925,0.365555,...,3,0.112182,0.040096,4,0.109686,0.017009,1,0.115210,0.388024,banking77
7,MATAVE,6.055634e-03,0.176033,0.991870,0.337082,0.716313,0.469054,0.637870,0.882104,0.445697,...,3,0.112182,0.048887,4,0.109686,0.025445,1,0.115210,0.494375,banking77
8,combinedTopicModel,9.495060e-01,0.165787,0.934553,0.322378,0.623337,0.340998,0.442302,0.660813,0.396567,...,3,0.112182,0.043498,4,0.109686,0.021466,1,0.115210,0.462397,banking77
9,realToReal,1.000000e+00,0.018521,0.609782,0.258443,0.365246,0.038515,0.007754,0.028652,0.154659,...,3,0.112182,0.016964,4,0.109686,0.009707,1,0.115210,0.203469,banking77
10,realToReal2,1.000000e+00,0.015009,0.347368,0.255469,0.359308,0.025145,0.013050,0.028431,0.164521,...,3,0.112182,0.018046,4,0.109686,0.009138,1,0.115210,0.181244,banking77
11,realToReal3,9.995537e-01,0.013292,0.490507,0.262185,0.368075,0.047055,0.006717,0.037632,0.152546,...,3,0.112182,0.016732,4,0.109686,0.009336,1,0.115210,0.195382,banking77
12,LDA,0.000000e+00,0.014930,0.821622,0.354773,0.708207,0.159788,0.034525,0.285763,0.501198,...,4,0.115109,0.056900,5,0.113528,0.065815,1,0.123627,0.365378,medicalAbstracts
13,MATAVE,0.000000e+00,0.004101,0.905602,0.360913,0.972905,0.501161,0.197862,0.955450,0.533052,...,4,0.115109,0.060516,5,0.113528,0.061116,1,0.123627,0.532347,medicalAbstracts
14,combinedTopicModel,0.000000e+00,0.004346,0.837463,0.354339,0.696929,0.163132,0.032745,0.189518,0.552586,...,4,0.115109,0.062734,5,0.113528,0.064255,1,0.123627,0.358116,medicalAbstracts
15,realToReal,1.000000e+00,0.006567,0.452991,0.351541,0.616568,0.038377,0.022810,0.013975,0.160999,...,4,0.115109,0.018278,5,0.113528,0.013077,1,0.123627,0.180260,medicalAbstracts
16,realToReal2,1.000000e+00,0.004054,0.455447,0.352545,0.611546,0.020187,0.028161,0.010134,0.206996,...,4,0.115109,0.023500,5,0.113528,0.013673,1,0.123627,0.183792,medicalAbstracts
17,realToReal3,1.000000e+00,0.011087,0.449163,0.356777,0.629965,0.028568,0.035317,0.021185,0.188316,...,4,0.115109,0.021379,5,0.113528,0.014057,1,0.123627,0.187416,medicalAbstracts
18,LDA,0.000000e+00,0.275123,1.000000,0.268766,0.528872,0.971628,0.945400,0.994716,0.831707,...,2,0.118130,0.093182,7,0.112037,0.034143,3,0.117260,0.664658,dementiaAudio
19,MATAVE,0.000000e+00,0.408289,1.000000,0.298694,0.678668,0.918791,0.985177,0.991864,0.742608,...,2,0.118130,0.083200,7,0.112037,0.029121,3,0.117260,0.683641,dementiaAudio
20,combinedTopicModel,0.000000e+00,0.331092,1.000000,0.279785,0.554763,0.856502,0.953449,0.989917,0.760059,...,2,0.118130,0.085155,7,0.112037,0.030551,3,0.117260,0.651121,dementiaAudio
21,realToReal,1.000000e+00,0.012869,0.502874,0.225210,0.246963,0.215590,0.067963,0.042560,0.185468,...,2,0.118130,0.020779,7,0.112037,0.010789,3,0.117260,0.169262,dementiaAudio
22,realToReal2,1.000000e+00,0.012835,0.517491,0.224534,0.244026,0.221586,0.061010,0.052462,0.156498,...,2,0.118130,0.017534,7,0.112037,0.009481,3,0.117260,0.166789,dementiaAudio
23,realToReal3,1.000000e+00,0.009173,0.556511,0.223291,0.244400,0.204767,0.005042,0.037800,0.193094,...,2,0.118130,0.021634,7,0.112037,0.012071,3,0.117260,0.167290,dementiaAudio
24,LDA,1.000000e+00,0.094843,0.903994,0.398165,0.932179,0.256034,0.113738,0.668309,0.408341,...,6,0.113252,0.048512,5,0.118802,0.032474,1,0.124268,0.414248,huffPostNews
25,MATAVE,9.999413e-01,0.072751,0.933262,0.391973,0.914629,0.685871,0.069518,0.715154,0.596367,...,6,0.113252,0.070850,5,0.118802,0.041399,1,0.124268,0.495632,huffPostNews
26,combinedTopicModel,1.000000e+00,0.074481,0.889925,0.399336,0.916891,0.350187,0.094235,0.708863,0.452646,...,6,0.113252,0.053775,5,0.118802,0.032751,1,0.124268,0.428560,huffPostNews
27,realToReal,1.000000e+00,0.012715,0.485879,0.397893,0.825248,0.047104,0.056485,0.035705,0.158042,...,6,0.113252,0.018776,5,0.118802,0.013515,1,0.124268,0.203219,huffPostNews
28,realToReal2,1.000000e+00,0.008621,0.514595,0.397513,0.816921,0.030260,0.042072,0.046989,0.182643,...,6,0.113252,0.021698,5,0.118802,0.011681,1,0.124268,0.203378,huffPostNews
29,realToReal3,1.000000e+00,0.017338,0.429221,0.399145,0.822369,0.047402,0.059454,0.015851,0.152946,...,6,0.113252,0.018170,5,0.118802,0.011817,1,0.124268,0.194068,huffPostNews
30,LDA,3.333420e-01,0.040010,0.905848,0.370837,0.903597,0.370109,0.267718,0.856025,0.297910,...,1,0.125164,0.035410,4,0.118861,0.027414,5,0.118708,0.445231,clinc150
31,MATAVE,7.818290e-02,0.092056,0.908059,0.365799,0.918988,0.485963,0.192195,0.885654,0.287830,...,1,0.125164,0.034212,4,0.118861,0.023754,5,0.118708,0.455824,clinc150
32,combinedTopicModel,2.151746e-01,0.025822,0.858749,0.369956,0.900922,0.393968,0.210487,0.850187,0.302133,...,1,0.125164,0.035912,4,0.118861,0.025242,5,0.118708,0.432537,clinc150
33,realToReal,1.000000e+00,0.011899,0.513418,0.344821,0.705288,0.048500,0.033357,0.032981,0.149495,...,1,0.125164,0.017769,4,0.118861,0.011485,5,0.118708,0.185817,clinc150
34,realToReal2,1.000000e+00,0.014937,0.569758,0.338226,0.702489,0.031744,0.026893,0.029132,0.151305,...,1,0.125164,0.017984,4,0.118861,0.010709,5,0.118708,0.186514,clinc150
35,realToReal3,1.000000e+00,0.010114,0.596101,0.346390,0.713181,0.058700,0.043301,0.036017,0.166320,...,1,0.125164,0.019769,4,0.118861,0.008344,5,0.118708,0.195401,clinc150
36,LDA,1.776357e-15,0.014840,0.950396,0.313259,0.675701,0.687813,0.222372,0.774940,0.681963,...,1,0.115990,0.073856,4,0.108300,0.027415,2,0.113719,0.473632,syntheticCareHomeNurseNotes
37,MATAVE,5.827899e-01,0.120457,0.832427,0.308065,0.544897,0.197927,0.224177,0.314331,0.475706,...,1,0.115990,0.051519,4,0.108300,0.011450,2,0.113719,0.349954,syntheticCareHomeNurseNotes
38,combinedTopicModel,7.251117e-01,0.099836,0.889588,0.307831,0.537559,0.197901,0.126569,0.145305,0.513120,...,1,0.115990,0.055571,4,0.108300,0.018346,2,0.113719,0.342558,syntheticCareHomeNurseNotes
39,realToReal,6.425657e-01,0.024013,0.532011,0.291150,0.419830,0.046790,0.039335,0.037413,0.156743,...,1,0.115990,0.016975,4,0.108300,0.009986,2,0.113719,0.200309,syntheticCareHomeNurseNotes
40,realToReal2,6.666947e-01,0.019438,0.445422,0.291032,0.417973,0.033557,0.008770,0.043537,0.181092,...,1,0.115990,0.019612,4,0.108300,0.009819,2,0.113719,0.192186,syntheticCareHomeNurseNotes
41,realToReal3,1.000000e+00,0.002707,0.459459,0.293564,0.423811,0.035180,0.029950,0.035616,0.150748,...,1,0.115990,0.016326,4,0.108300,0.011396,2,0.113719,0.212899,syntheticCareHomeNurseNotes
42,LDA,1.804066e-02,0.067664,0.882244,0.324126,0.700172,0.346687,0.152044,0.670578,0.317777,...,7,0.106291,0.036317,4,0.114284,0.034939,3,0.120696,0.396322,clinicalDialogueSummarizations
43,MATAVE,8.768662e-02,0.174165,0.884921,0.343103,0.754790,0.322953,0.491114,0.660508,0.373124,...,7,0.106291,0.042642,4,0.114284,0.045758,3,0.120696,0.468169,clinicalDialogueSummarizations
44,combinedTopicModel,8.194380e-01,0.109620,0.844266,0.329221,0.692824,0.275295,0.224693,0.446787,0.330613,...,7,0.106291,0.037784,4,0.114284,0.037107,3,0.120696,0.377159,clinicalDialogueSummarizations
45,realToReal,1.000000e+00,0.008507,0.433427,0.268679,0.471876,0.075303,0.043239,0.035384,0.180081,...,7,0.106291,0.020580,4,0.114284,0.013021,3,0.120696,0.168958,clinicalDialogueSummarizations
46,realToReal2,1.000000e+00,0.007129,0.524975,0.263907,0.479710,0.081820,0.079033,0.070449,0.148069,...,7,0.106291,0.016922,4,0.114284,0.013034,3,0.120696,0.182283,clinicalDialogueSummarizations
47,realToReal3,1.000000e+00,0.009529,0.523699,0.268450,0.478067,0.066987,0.085916,0.024512,0.176323,...,7,0.106291,0.020151,4,0.114284,0.011580,3,0.120696,0.178678,clinicalDialogueSummarizations
48,LDA,0.000000e+00,0.065586,0.948246,0.238410,0.453070,0.703834,0.914490,0.850609,0.487842,...,8,0.097272,0.055978,5,0.114746,0.041799,6,0.114293,0.540772,simSUM
49,MATAVE,0.000000e+00,0.153250,0.975580,0.241777,0.516674,0.708391,0.899407,0.879122,0.506891,...,8,0.097272,0.058164,5,0.114746,0.040653,6,0.114293,0.564177,simSUM
50,combinedTopicModel,0.000000e+00,0.126356,0.958913,0.237296,0.429561,0.684556,0.894699,0.608304,0.537282,...,8,0.097272,0.061651,5,0.114746,0.039329,6,0.114293,0.521268,simSUM
51,realToReal,1.000000e+00,0.006168,0.543346,0.171518,0.146968,0.087157,0.020543,0.031643,0.158191,...,8,0.097272,0.018152,5,0.114746,0.012281,6,0.114293,0.133216,simSUM
52,realToReal2,1.000000e+00,0.008202,0.552635,0.171034,0.148491,0.076661,0.027608,0.019644,0.137703,...,8,0.097272,0.015801,5,0.114746,0.009397,6,0.114293,0.127582,simSUM
53,realToReal3,1.000000e+00,0.008179,0.491062,0.174633,0.157546,0.092484,0.015280,0.088886,0.151926,...,8,0.097272,0.017433,5,0.114746,0.009734,6,0.114293,0.132647,simSUM
54,LDA,0.000000e+00,0.160100,0.924510,0.273549,0.499266,0.445983,0.649656,0.930024,0.391046,...,7,0.096971,0.044293,2,0.113267,0.033265,1,0.118169,0.456000,atis
55,MATAVE,0.000000e+00,0.214378,0.965789,0.291243,0.556121,0.451170,0.812388,0.820226,0.367406,...,7,0.096971,0.041615,2,0.113267,0.024361,1,0.118169,0.466121,atis
56,combinedTopicModel,0.000000e+00,0.194480,0.925578,0.278564,0.500423,0.381192,0.716741,0.879474,0.361791,...,7,0.096971,0.040979,2,0.113267,0.027457,1,0.118169,0.445000,atis
57,realToReal,1.000000e+00,0.034241,0.492565,0.222348,0.246657,0.077028,0.109284,0.072197,0.157731,...,7,0.096971,0.017866,2,0.113267,0.007806,1,0.118169,0.210361,atis
58,realToReal2,6.666748e-01,0.026406,0.570469,0.223348,0.249913,0.089978,0.015758,0.028859,0.162957,...,7,0.096971,0.018458,2,0.113267,0.008157,1,0.118169,0.185810,atis
59,realToReal3,7.355493e-01,0.012060,0.478451,0.223697,0.236463,0.070448,0.016289,0.019121,0.160675,...,7,0.096971,0.018199,2,0.113267,0.008341,1,0.118169,0.176097,atis

In [7]:
calibrated_results.to_csv('./generalizability.csv')

In [8]:
ranked_dict_results = []
for dataset in calibrated_results['dataset'].unique():
    subset = calibrated_results[calibrated_results['dataset'] == dataset]
    # Extract not real rows.
    real_mask = subset['model'].str.startswith('real')
    subset = subset.loc[~real_mask]
    ranks = subset['final_score'].rank(
        ascending=True,
        method='dense'
    ).astype(int)
    ranked_dict_results.append(pd.DataFrame({
        'model': subset['model'].values,
        'dataset': dataset,
        'final_score': subset['final_score'].values,
        'rank': ranks.values
    }))

In [9]:
ranked_results_df = pd.concat(ranked_dict_results)
ranked_results_df = ranked_results_df[
    (ranked_results_df['dataset'] != 'syntheticCareHomeNurseNotes') & 
    (ranked_results_df['dataset'] != 'atis') & 
    (ranked_results_df['dataset'] != 'clinc150')
    ]

In [10]:
ranked_results_df[ranked_results_df['rank'] == 1]['model'].value_counts()

model
combinedTopicModel    5
LDA                   2
Name: count, dtype: int64