In [1]:
import pandas as pd
import readability
import os
import numpy as np
import random
import torch
from bert_score import BERTScorer
import re
from nltk.translate import meteor
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from textblob import TextBlob
import math

In [2]:
from transformers import logging
logging.set_verbosity_error() # make sure only important transformers logging output is visible

In [3]:
# Only need to run once.
# nltk.download('all')

In [4]:
# Set random states.
def set_random_states(random_state):
    # Set various random seeds.
    np.random.seed(random_state)
    pd.core.common.random_state(random_state)
    random.seed(random_state)
    torch.manual_seed(random_state)
    torch.cuda.manual_seed_all(random_state)
    os.environ["PYTHONHASHSEED"] = str(random_state)
    os.environ["TOKENIZERS_PARALLELISM"] = "false"
    try:
        torch.use_deterministic_algorithms(True)
    except Exception:
        pass
    return random_state

RANDOM_STATE = set_random_states(1618)

In [5]:
OUTPUT_DIR = 'outputScores/'

In [6]:
def preprocess_text(text):
    text = re.sub(r'[^\w\s/]', '', text)
    # tokenize
    tokens = word_tokenize(text.lower())
    # remove stop words
    filtered_tokens = [token for token in tokens if token not in stopwords.words('english')]
    # lemmatize the tokens
    lemmatizer = WordNetLemmatizer()
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in filtered_tokens]
    # join the tokens back into a string
    processed_text = ' '.join(lemmatized_tokens)
    return processed_text

In [7]:
generation_types = ['fakeLocal', 'fakeOnlineGPT3', 'fakeOnlineGPT4']
input_prompt_paths = ['./dataGeneration/syntheticNotesLocal/fakeNoteGeneration/fake_notes.xlsx', './dataGeneration/syntheticNotesLocal/fakeNoteGeneration/fake_notes.xlsx', './dataGeneration/syntheticNotesLocal/fakeNoteGeneration/fake_notes.xlsx']
input_generated_data_dirs = ['dataGeneration/syntheticNotesLocal/fakeNoteGeneration/processedFakeNoteSyntheticNotes', 'dataGeneration/syntheticNotesOnline/gpt3Notes', 'dataGeneration/syntheticNotesOnline/gpt4Notes']

In [8]:
def make_score_df(generation_type, input_prompt_path, input_generated_data_dir):
    prompt_df = pd.read_excel(input_prompt_path)
    average_scores_dict = []
    # Make BERT scorer.
    scorer = BERTScorer(model_type="bert-base-uncased")
    for dataset in os.listdir(f"./{input_generated_data_dir}"):
        if dataset.endswith('.csv'):
            temp_df = pd.read_csv(f"./{input_generated_data_dir}/{dataset}")
            temp_split = dataset.split('_')
            prompt_number, prompt_needs = temp_split[0], temp_split[1].replace('.csv', '')
            temp_prompt = prompt_df[prompt_df['Needs'] == prompt_needs]['Note'].tolist()[int(prompt_number)]
            # --------- Readability (number linked to grade of reading level)s ---------
            references = []
            candidates = []
            meteors = []
            sentiments = []
            subjectivities = []
            abs_sentiment_diffs = []
            abs_subjectivity_diffs = []
            # Make readability metric.
            preprocessed_prompt = preprocess_text(temp_prompt)
            reference_blob = TextBlob(preprocessed_prompt)
            for temp_generation in temp_df['report'].tolist():
                processed_generation = preprocess_text(temp_generation)
                candidate_blob = TextBlob(processed_generation)
                if candidate_blob.sentences and reference_blob.sentences:
                    # Make candidates and references without punctuation for metrics (BERTScore penalizes punctuation, we should take this into account - https://aclanthology.org/2023.findings-acl.381.pdf).
                    reference = re.sub(r'[^\w\s/]', '', temp_prompt)
                    candidate = re.sub(r'[^\w\s/]', '', temp_generation)
                    references.append(reference)
                    candidates.append(candidate)
                    sentiments.append(candidate_blob.sentences[0].sentiment.polarity)
                    subjectivities.append(candidate_blob.sentences[0].sentiment.subjectivity)
                    # Make METEOR
                    meteors.append(meteor([word_tokenize(candidate)], word_tokenize(reference)))
                    # Make sentiment and subjectivity absolute differences.                    
                    abs_sentiment_diffs.append(math.sqrt((reference_blob.sentences[0].sentiment.polarity - candidate_blob.sentences[0].sentiment.polarity) ** 2))
                    abs_subjectivity_diffs.append(math.sqrt((reference_blob.sentences[0].sentiment.subjectivity - candidate_blob.sentences[0].sentiment.subjectivity) ** 2))

            # Make BERTScore
            _, _, F1 = scorer.score(candidates, references)

            average_scores_dict.append({
                'dataset': dataset.replace('.csv', ''), 
                'needs': prompt_needs,
                'generation_type': generation_type,
                'number_of_notes': len(temp_df),
                # save the F1 values, as these are recommended for use by the BERTScore authors - http://arxiv.org/abs/1904.09675
                'bertscore': float(F1.mean()),
                'meteor': sum(meteors) / len(meteors),
                'sentiment': sum(sentiments) / len(sentiments),
                'subjectivity': sum(subjectivities) / len(subjectivities),
                'abs_sentiment_diff': sum(abs_sentiment_diffs) / len(abs_sentiment_diffs),
                'abs_subjectivity_diff': sum(abs_subjectivity_diffs) / len(abs_subjectivity_diffs)})
            
    # min-max normalize every score
    resultant_df = pd.DataFrame(average_scores_dict)
    return resultant_df

In [9]:
all_dfs = []
for generation_type, input_prompt_path, input_generated_data_dir in zip(generation_types, input_prompt_paths, input_generated_data_dirs):
    all_dfs.append(make_score_df(generation_type, input_prompt_path, input_generated_data_dir))

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [10]:
combined_df = pd.concat(all_dfs)

In [11]:
scaled_df = combined_df.copy()

metric_cols = [
    "bertscore",
    "meteor",
    "abs_sentiment_diff",
    "abs_subjectivity_diff"
]

# Min-max normalize safely.
for col in metric_cols:
    min_val = scaled_df[col].min()
    max_val = scaled_df[col].max()

    if max_val - min_val == 0:
        scaled_df[col] = 0.0
    else:
        scaled_df[col] = (scaled_df[col] - min_val) / (max_val - min_val)

# Invert the lower is better columns.
lower_is_better = [
    "abs_sentiment_diff",
    "abs_subjectivity_diff"
]

for col in lower_is_better:
    scaled_df[col] = 1 - scaled_df[col]

# Get overall scores.
scaled_df["overall_score"] = scaled_df[[
    "bertscore",
    "meteor",
    "abs_sentiment_diff",
    "abs_subjectivity_diff"
]].mean(axis=1)

# Get final summary table.
summary = (
    scaled_df
    .groupby(["generation_type"])["overall_score"]
    .mean()
    .reset_index()
    .sort_values(["overall_score"], ascending=False)
)

# Save outputs. 
os.makedirs(f'./{OUTPUT_DIR}/', exist_ok=True)
scaled_df.to_csv(f'./{OUTPUT_DIR}/evaluated_scaled_results.csv', index=False)
combined_df.to_csv(f'./{OUTPUT_DIR}/raw_evaluation_results.csv', index=False)
summary.to_csv(f'./{OUTPUT_DIR}/dataset_summary.csv', index=False)

In [12]:
print("------ Summary Performance ------")
summary

------ Summary Performance ------

  generation_type  overall_score
0       fakeLocal       0.616773
1  fakeOnlineGPT3       0.546350
2  fakeOnlineGPT4       0.537258

In [13]:
print("------ Scaled Scores ------")
scaled_df.sort_values(by='overall_score', ascending=False)

------ Scaled Scores ------

,dataset,needs,generation_type,number_of_notes,bertscore,meteor,sentiment,subjectivity,abs_sentiment_diff,abs_subjectivity_diff,overall_score
8,4_met,met,fakeOnlineGPT3,588,1.000000,1.000000,0.084496,0.292322,0.726939,0.773028,0.874992
9,1_unmet,unmet,fakeLocal,210,0.901011,0.339117,-0.007766,0.380985,0.968051,1.000000,0.802045
5,3_met,met,fakeOnlineGPT4,636,0.773509,0.591258,0.097503,0.371358,0.828206,0.846005,0.759745
8,4_met,met,fakeLocal,170,0.893242,0.624549,0.086177,0.361225,0.810950,0.649272,0.744503
3,4_unmet,unmet,fakeLocal,241,0.688379,0.584248,0.006554,0.366239,1.000000,0.663719,0.734086
0,0_met,met,fakeOnlineGPT4,628,0.623887,0.516248,0.099817,0.417302,0.845186,0.942322,0.731911
5,3_met,met,fakeOnlineGPT3,570,0.834048,0.651159,0.214944,0.430629,0.650796,0.716521,0.713131
9,1_unmet,unmet,fakeOnlineGPT4,643,0.675712,0.330829,0.047549,0.385867,0.877794,0.868597,0.688233
5,3_met,met,fakeLocal,272,0.602803,0.416450,0.144183,0.424871,0.848556,0.795258,0.665767
0,0_met,met,fakeOnlineGPT3,594,0.562118,0.564981,0.168317,0.435939,0.641064,0.844558,0.653180
0,0_met,met,fakeLocal,216,0.536159,0.424033,0.195341,0.465887,0.690990,0.960976,0.653039
9,1_unmet,unmet,fakeOnlineGPT3,571,0.550502,0.326918,0.038067,0.337272,0.891146,0.699728,0.617073
4,3_unmet,unmet,fakeLocal,238,0.663193,0.314122,0.050599,0.377065,0.953006,0.503253,0.608393
2,1_met,met,fakeLocal,228,0.583869,0.364419,0.202675,0.450829,0.550805,0.890014,0.597277
1,2_unmet,unmet,fakeOnlineGPT4,642,0.476531,0.238376,0.055206,0.358362,0.831623,0.794439,0.585242
6,2_met,met,fakeLocal,232,0.519179,0.173788,0.208057,0.470148,0.820408,0.754057,0.566858
1,2_unmet,unmet,fakeLocal,278,0.399211,0.132254,0.022852,0.374026,0.875603,0.851076,0.564536
3,4_unmet,unmet,fakeOnlineGPT4,620,0.286379,0.402993,0.068027,0.351760,0.877010,0.680475,0.561714
6,2_met,met,fakeOnlineGPT4,637,0.469813,0.244963,0.132416,0.397494,0.712101,0.805883,0.558190
3,4_unmet,unmet,fakeOnlineGPT3,578,0.185379,0.383759,0.042016,0.295451,0.930013,0.711325,0.552619
4,3_unmet,unmet,fakeOnlineGPT4,640,0.428608,0.289801,0.077209,0.358619,0.884388,0.540861,0.535915
1,2_unmet,unmet,fakeOnlineGPT3,553,0.342313,0.231256,0.038605,0.313107,0.850841,0.649826,0.518559
4,3_unmet,unmet,fakeOnlineGPT3,598,0.176395,0.121118,0.051434,0.281890,0.910126,0.697304,0.476236
8,4_met,met,fakeOnlineGPT4,587,0.325239,0.312953,0.121355,0.391147,0.668968,0.589575,0.474184
6,2_met,met,fakeOnlineGPT3,577,0.334940,0.244063,0.218285,0.424868,0.637363,0.674442,0.472702
2,1_met,met,fakeOnlineGPT3,575,0.215257,0.335234,0.212531,0.372658,0.430861,0.663249,0.411150
2,1_met,met,fakeOnlineGPT4,610,0.267108,0.249360,0.127197,0.378488,0.352151,0.769321,0.409485
7,0_unmet,unmet,fakeLocal,300,0.545404,0.080734,-0.011179,0.382385,0.000000,0.298749,0.231222
7,0_unmet,unmet,fakeOnlineGPT3,579,0.435651,0.141134,0.038090,0.240403,0.118644,0.000000,0.173857
7,0_unmet,unmet,fakeOnlineGPT4,610,0.000000,0.000000,0.048476,0.310257,0.121652,0.150175,0.067957

In [14]:
print("------ Raw Dataframe ------")
combined_df

------ Raw Dataframe ------

,dataset,needs,generation_type,number_of_notes,bertscore,meteor,sentiment,subjectivity,abs_sentiment_diff,abs_subjectivity_diff
0,0_met,met,fakeLocal,216,0.510298,0.156667,0.195341,0.465887,0.213263,0.152570
1,2_unmet,unmet,fakeLocal,278,0.495886,0.097852,0.022852,0.374026,0.146848,0.206472
2,1_met,met,fakeLocal,228,0.515319,0.144650,0.202675,0.450829,0.263694,0.187374
3,4_unmet,unmet,fakeLocal,241,0.526317,0.188962,0.006554,0.366239,0.102096,0.298363
4,3_unmet,unmet,fakeLocal,238,0.523667,0.134512,0.050599,0.377065,0.119002,0.377065
5,3_met,met,fakeLocal,272,0.517312,0.155138,0.144183,0.424871,0.156578,0.233848
6,2_met,met,fakeLocal,232,0.508511,0.106224,0.208057,0.470148,0.166704,0.254056
7,0_unmet,unmet,fakeLocal,300,0.511271,0.087467,-0.011179,0.382385,0.461846,0.477365
8,4_met,met,fakeLocal,170,0.547876,0.197086,0.086177,0.361225,0.170107,0.305448
9,1_unmet,unmet,fakeLocal,210,0.548694,0.139550,-0.007766,0.380985,0.113590,0.133431
0,0_met,met,fakeOnlineGPT3,594,0.513030,0.185079,0.168317,0.435939,0.231223,0.209669
1,2_unmet,unmet,fakeOnlineGPT3,553,0.489899,0.117808,0.038605,0.313107,0.155756,0.305177
2,1_met,met,fakeOnlineGPT3,575,0.476528,0.138767,0.212531,0.372658,0.306844,0.298593
3,4_unmet,unmet,fakeOnlineGPT3,578,0.473384,0.148549,0.042016,0.295451,0.127274,0.275014
4,3_unmet,unmet,fakeOnlineGPT3,598,0.472438,0.095607,0.051434,0.281890,0.134428,0.281890
5,3_met,met,fakeOnlineGPT3,570,0.541647,0.202450,0.214944,0.430629,0.227722,0.272465
6,2_met,met,fakeOnlineGPT3,577,0.489123,0.120390,0.218285,0.424868,0.232555,0.293103
7,0_unmet,unmet,fakeOnlineGPT3,579,0.499721,0.099642,0.038090,0.240403,0.419164,0.623889
8,4_met,met,fakeOnlineGPT3,588,0.559111,0.272767,0.084496,0.292322,0.200330,0.244751
9,1_unmet,unmet,fakeOnlineGPT3,571,0.511808,0.137091,0.038067,0.337272,0.141256,0.280701
0,0_met,met,fakeOnlineGPT4,628,0.519530,0.175255,0.099817,0.417302,0.157790,0.161719
1,2_unmet,unmet,fakeOnlineGPT4,642,0.504023,0.119243,0.055206,0.358362,0.162670,0.234250
2,1_met,met,fakeOnlineGPT4,610,0.481984,0.121457,0.127197,0.378488,0.335160,0.246569
3,4_unmet,unmet,fakeOnlineGPT4,620,0.484012,0.152426,0.068027,0.351760,0.146342,0.290144
4,3_unmet,unmet,fakeOnlineGPT4,640,0.498980,0.129609,0.077209,0.358619,0.143687,0.358619
5,3_met,met,fakeOnlineGPT4,636,0.535276,0.190375,0.097503,0.371358,0.163899,0.208959
6,2_met,met,fakeOnlineGPT4,637,0.503316,0.120571,0.132416,0.397494,0.205668,0.228637
7,0_unmet,unmet,fakeOnlineGPT4,610,0.453875,0.071193,0.048476,0.310257,0.418082,0.550234
8,4_met,met,fakeOnlineGPT4,587,0.488102,0.134276,0.121355,0.391147,0.221185,0.334727
9,1_unmet,unmet,fakeOnlineGPT4,643,0.524984,0.137879,0.047549,0.385867,0.146060,0.197878

In [15]:
# Global model comparison. 
global_summary = (
    scaled_df
    .groupby("generation_type")[[
        "bertscore",
        "meteor",
        "abs_sentiment_diff",
        "abs_subjectivity_diff",
        "overall_score"
    ]]
    .mean()
    .sort_values("overall_score", ascending=False)
)

In [16]:
print("\n------ Global Model Performance ------\n")
global_summary

------ Global Model Performance ------

,bertscore,meteor,abs_sentiment_diff,abs_subjectivity_diff,overall_score
generation_type,,,,,
fakeLocal,0.633245,0.345371,0.751837,0.736637,0.616773
fakeOnlineGPT3,0.463660,0.399962,0.678779,0.642998,0.546350
fakeOnlineGPT4,0.432679,0.317678,0.699908,0.698765,0.537258